my_string = input('Введите Ваше имя, фамилия и отчество (при наличии): ')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])